config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get 'pages/about', to: "pages#about"
  get 'pages/contact', to: "pages#contact"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :pages, only: [:create, :show]
  resources :packages, only: [:index, :show] do
    resources :payments, only: [:new, :create]
  end

  resources :face_treatments, only: [:index, :show] do
    resources :treatments, only: [:index, :new, :create]
  end

  resources :body_treatments, only: [:index, :show] do
    resources :treatments, only: [:index, :new, :create]
  end

  resources :hair_treatments, only: [:index, :show] do
    resources :treatments, only: [:index, :new, :create]
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/body_treatment.rb
class BodyTreatment < ApplicationRecord
  has_many :treatments, dependent: :nullify
end

app/models/face_treatment.rb
class FaceTreatment < ApplicationRecord
  has_many :treatments, dependent: :nullify
end

app/models/hair_treatment.rb
class HairTreatment < ApplicationRecord
  has_many :treatments, dependent: :nullify
end

app/models/package.rb
class Package < ApplicationRecord
  validates :package_name, presence: true
  validates :package_description, presence: true
  validates :package_price, presence: true
  validates :image, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :package

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, presence: true, numericality: { only_integer: true }
  validates :address, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :payment_date, presence: true
  validates :payment_amount, presence: true, numericality: { greater_than: 0 }
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :face_treatment, class_name: 'FaceTreatment'
  belongs_to :body_treatment, class_name: 'HairTreatment'
  belongs_to :hair_treatment, class_name: 'BodyTreatment'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/body_treatments_controller.rb
class BodyTreatmentsController < ApplicationController
  def index
    @body_treatments = BodyTreatment.all
  end

  def show
    @body_treatment = BodyTreatment.find(params[:id])
    @body_treatment = BodyTreatment.new
  end

  private

  def package_params
    params.require(:body_treatment).permit(:body_treatment_name, :body_treatment_description)
  end
end

app/controllers/face_treatments_controller.rb
class FaceTreatmentsController < ApplicationController
  def index
    @face_treatments = FaceTreatment.all
  end

  def show
    @face_treatment = FaceTreatment.find(params[:id])
    @face_treatment = FaceTreatment.new
  end

  private

  def package_params
    params.require(:face_treatment).permit(:face_treatment_name, :face_treatment_description)
  end
end

app/controllers/hair_treatments_controller.rb
class HairTreatmentsController < ApplicationController
  def index
    @hair_treatments = HairTreatment.all
  end

  def show
    @hair_treatment = HairTreatment.find(params[:id])
    @hair_treatment = HairTreatment.new
  end

  private

  def package_params
    params.require(:hair_treatment).permit(:hair_treatment_name, :hair_treatment_description)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def index
    @packages = Package.all
  end

  def show
    @package = Package.find(params[:id])
    @payment = Payment.new
  end

  private

  def package_params
    params.require(:package).permit(:package_name, :package_description, :package_price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @packages = Package.all
  end

  def about
  end

  def contact
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    # @package = package.find(params[:package_id])
    @payment = Payment.new(payment_params)
  end

  def create
    @package = package.find(params[:package_id])
    @payment = Payment.new(payment_params)
    # @payment.recipe = @package
    if @payment.save
      redirect_to package_path(@package)
    else
      render 'package/show'
    end
  end

  private

  def payment_params
    params.permit(:first_name, :last_name, :email, :phone, :address, :city, :country)
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  def index
    @treatments = Treatment.all
  end

  def new
    @treatment = Treatment.new
  end

  def create
    @treatment = Treatment.new(treatment_params)
    if @treatment.save
      redirect_to treatment_path(@treatment)
    else
      render 'treatment/show'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/body_treatments/index.html.erb
<div class="container">
  <h1 class="mb-5 d-flex justify-content-center">Body Treatments</h1>

   <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
     <% @body_treatments.each do |body_treatment| %>
      <div class="col d-flex justify-content-center">
        <div class="card-package mb-5">
          <%= image_tag "3.png" %>
          <div class="card-package-infos">
            <h2 class="my-3 fw-normal"><%= body_treatment.body_treatment_name %></h2>
            <p><%= body_treatment.body_treatment_description %></p>
            <%= link_to "Read more", "", class: "mt-6" %>
          </div>
        </div>
      </div>
      <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cosmed Travel | Book your surgery in Azerbaijan.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= yield %>

    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="text-center">About us</h1>
    <p class="col-md-10">We offer a wide range of carefully curated packages that cater to different needs and goals. Whether you're looking for a complete makeover, a specific treatment, or a rejuvenating experience, our packages are designed to provide you with a comprehensive and personalized aesthetic travel experience.</p>
    <div class="col-md-10 text-center">
      <%= image_tag "7.png", class: "img-fluid mb-4" %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <h1 class="d-flex justify-content-center mb-4">Contact us</h1>


<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. <br>Our team will come back to you within a matter of hours to help you.</p>

    <div class="row d-flex justify-content-center">

        <!--Grid column-->
        <div class="col-md-5 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-4">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-4">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-4">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-lg btn-primary mb-5 mt-4" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Baku, Azerbaijan, AZ1001</p>
                </li>

                <li><i class="fas fa-phone mt-2 fa-2x"></i>
                    <p>+994 50 000 00 00</p>
                </li>

                <li><i class="fas fa-envelope mt-2 fa-2x"></i>
                    <p>contact@cosmedtravel.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->

</div>

app/views/pages/home.html.erb
<div class="container">

  <div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">

    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>

    <div class="carousel-inner">

      <div class="carousel-item active" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= asset_path('5.png') %>);">
        <div class="container">
          <div class="carousel-caption text-start">
            <h1 class="pb-2">Your trusted aesthetic travel agency in Azerbaijan</h1>
            <p>Life is too short not to have the body you deserve. <br> Cosmed Travel is a medical tourism agency, providing you with the best available treatment - in a safe, supportive environment.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Book your package</a></p>
          </div>
        </div>
      </div>

      <div class="carousel-item" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= asset_path('7.png') %>);">
        <div class="container">
          <div class="carousel-caption">
            <h1 class="pb-2">Exceptional quality and affordable prices</h1>
            <p>Save time, money and stress - without compromising on the quality of your healthcare. <br>We can cater for most price points and ensure you get the best outcome.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Explore treatments</a></p>
          </div>
        </div>
      </div>

      <div class="carousel-item" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= asset_path('10.png') %>);">
        <div class="container">
          <div class="carousel-caption text-end">
            <h1 class="pb-2">One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Online consultation</a></p>
          </div>
        </div>
      </div>

    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <section class="wrapper">
    <div class="container">
      <div class="row">
        <div class="cards col text-center mb-3">
          <h1 class="fw-normal text-uppercase mt-4">Selection of Treatments</h1>
            <p class="fs-6 text-muted mt-4">We offer a wide range of carefully curated packages that cater to different needs and goals. Whether you're looking for a complete makeover, a specific treatment, or a rejuvenating experience, our packages are designed to provide you with a comprehensive and personalized aesthetic travel experience. </p>
        </div>
      </div>

      <div class="row">

      <% treatments = ["face", "body", "hair"] %>

      <% treatments.each do |treatment| %>
        <% image_path = case treatment
                      when "face"
                        asset_path('1.png')
                      when "body"
                        asset_path('3.png')
                      when "hair"
                        asset_path('11.webp')
                      else
                        asset_path('1.png')
                      end %>
        <div class="col-sm-12 col-md-6 col-lg-4 mt-4 mb-4 d-flex justify-content-center">
          <div class="card text-white card-has-bg click-col" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= image_path %>);">
            <img class="card-img d-none" alt="<%= treatment.capitalize %> Treatment">
            <div class="card-img-overlay d-flex flex-column">
              <div class="card-body d-flex align-items-center">
                <h1 class="mx-auto"> <%= treatment.upcase %></h1>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </section>

  <div class="container services px-4 py-5" id="hanging-icons">
    <h1 class="pb-2 border-bottom text-center text-uppercase">Our Services</h1>
    <div class="row g-5 pt-5 pb-3 row-cols-1 row-cols-lg-4">
      <div class="col d-flex align-items-start">
        <div class="icon-square text-dark flex-shrink-0 me-3 pt-1">
          <i class="fa-solid fa-plane fa-2xl"></i>
        </div>
        <div>
          <h3>Travel Schedules</h3>
          <p>You will have a dedicated Client Consultant who will create a bespoke itinerary for you and guide you throughout the entire process.</p>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square text-dark flex-shrink-0 me-3 pt-1">
            <i class="fa-solid fa-user-doctor fa-2xl"></i>
        </div>
        <div>
          <h3>Medical Arrangements</h3>
          <p>You will have a dedicated Client Consultant who will create a bespoke itinerary for you and guide you throughout the entire process.</p>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square text-dark flex-shrink-0 me-3 pt-1">
          <i class="fa-solid fa-hotel fa-2xl"></i>
        </div>
        <div>
          <h3>Accommodation Booking</h3>
          <p>You will have a dedicated Client Consultant who will create a bespoke itinerary for you and guide you throughout the entire process.</p>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square bg-light text-dark flex-shrink-0 me-3 pt-1">
          <i class="fa-solid fa-building-columns fa-2xl"></i>
        </div>
        <div>
          <h2>Tours and Excursions</h2>
          <p>You will have a dedicated Client Consultant who will create a bespoke itinerary for you and guide you throughout the entire process.</p>
        </div>
      </div>
    </div>
      <div class="d-flex justify-content-center text-center pb-5">
        <a class="btn btn-lg btn-primary text-transform-light" href="#">About Us</a>
      </div>
  </div>

</div>

app/views/payments/new.html.erb
<h1>Booking form</h1>

<%= simple_form_for(@payment, :url => new_package_payment_path, :method => :post) do |f| %>

  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :country, as: :country %>
  <%= f.submit "Submit the booking" %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer text-center text-lg-start bg-light text-muted pt-5">

  <section class="footer-info">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Cosmed Travel
          </h6>
          <p>
            Your trusted aesthetic tourism agency in Azerbaijan.
          </p>

            <div class="social-icons justify-content-center">
              <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="" class="me-4 text-reset">
                <i class="fab fa-tiktok"></i>
              </a>
              <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
              </a>
          </div>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="packages col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Packages
          </h6>
          <p>
            <a href="/packages/1" class="text-reset">Aesthetic Surgery</a>
          </p>
          <p>
            <a href="/packages/2" class="text-reset">Weight-loss Surgery</a>
          </p>
          <p>
            <a href="/packages/3" class="text-reset">Dental Surgery</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="useful-links col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="/packages" class="text-reset">Our Packages</a>
          </p>
          <p>
            <a href="/pages/about" class="text-reset">Abous Us</a>
          </p>
          <p>
            <a href="#" class="text-reset">Azerbaijan</a>
          </p>
          <p>
            <a href="#" class="text-reset">FAQ</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact Details</h6>
          <p><i class="fas fa-home me-3"></i>Baku, AZ1027</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@cosmedtravel.com
          </p>
          <p><i class="fas fa-phone me-3"></i> +994 00 000000</p>
          <p><i class="fas fa-phone me-3"></i> +44 000 000 00</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>

  <div class="text-center p-4 text-muted">
    © 2023 Cosmed Travel <i class="fas fa-heart"></i>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar navbar-expand-sm navbar-light navbar-cosmedtravel">
    <div class="container-fluid">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag("Logo-Cosmed-Travel-color.png", alt: "CosmedTravel") %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <%# if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home", "/", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Our Packages", "/packages", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About us", "/pages/about", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact us", "/pages/contact", class: "nav-link" %>
            </li>
            <%# <li class="nav-item dropdown"> %>
              <%# <i class="fa-solid fa-bars"></i><%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%# <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> %>
                <%# <%= link_to "Action", "#", class: "dropdown-item" %>
                <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%# <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# </div> %>
            <%# </li> %>
          <%# else %>
            <!--li class="nav-item"-->
              <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
            <!--/li-->
          <%# end %>
        </ul>
      </div>
    </div>
  </div>
</div>